README.ko.md
README.md

BDSX에 README를 일부 수정하고, 한국어  README를 넣었습니다.

README Updates & Add README.ko

---

bdsx/bds/packets.ts

set offsets for transferpacket to work properly

fix TransferPacket

---

bdsx/bds/packets.ts

Packet structure and offsets for AnimatePacket and PlayerHotbarPacket, has been tested and the offsets should be correct

AnimatePacket and PlayerHotbarPacket implementation

---

README.md

-t opens a TTY
-i keeps STDIN open even if not connected
Both are required to run via the command line.

Add Proper Docker Run Command

---

bdsx/bds/actor.ts
bdsx/bds/pdb.ini
bdsx/bds/symbols.ts
bdsx/event.ts

itemStack in PlayerPickupItemEvent is still not done, no clue why it didn't work

Add QueryRegenerateEvent and make event fields editable

---

bdsx/bds/form.ts

change defaultValue from boolean to string

fix FormInput

---

bdsx/bds/implements.ts
bdsx/bds/pdb.ini
bdsx/bds/server.ts
bdsx/bds/symbols.ts

I finally know how to put all files in one commit with vscode 😄

add ServerInstance.disconnectAllClients

---

bdsx/bds/form.ts

simple edit to the setTimeout timer in Form.sendTo

Fixed Button URL images not loading

---

bdsx/bds/packets.ts

idk if there is a better way to put and name the enums

some enums of packets

---

bdsx/bds/packets.ts
launcher.ts

Added OnScreenTextureAnimationPacket support, allowing to display screen animations like seen on [this video](https://streamable.com/7x0iaz).
Also added a BDSX Ascii art at startup, useless but I find it cool :p

OnScreenTextureAnimationPacket Support

---

bdsx/pluginmgr/new.ts
plugin-example/README.md

Fix newplugin (Update old exampleSource)

Fix newplugin (Update old exampleSource)

---

bdsx/bds/command.ts
bdsx/command.ts

The legacy CommandFlag enum is still kept (oops I forgot to deprecate it)

More command flags

---

bdsx/bds/packets.ts

Implement CompletedUsingItemPacket

Implement CompletedUsingItemPacket

---

bdsx/bds/packetids.ts
bdsx/bds/packets.ts
example_and_test/test.ts

- Implement PositionTrackingDBClientRequestPacket and PositionTrackingDBServerBroadcastPacket(Need improvement)
- Deprecate PositionTrackingDBClientRequest and PositionTrackingDBServerBroadcast

Implement PositionTrackingDB related packets

---

bdsx/bds/implements.ts
bdsx/bds/inventory.ts

This is a PR because we aren't 100% sure this isn't a memory leak, so @karikera please merge this if there is no leak.

Use CxxString instead of CxxStringWrapper

---

bdsx/bds/implements.ts
bdsx/bds/inventory.ts
bdsx/bds/pdb.ini
bdsx/bds/symbols.ts

PlayerInventory.getSlotWithItem
ItemStack.cloneItem
ItemStack.getMaxStackSize

Add some components.

---

bdsx.sh

Add the Shebang line to run this file on Linux

Add Shebang line

---

bdsx/util.ts

Would be nice for people who want to have it more like pm and useful in general

Add TextFormat like pocketmine?

---

bdsx/bds/actor.ts
bdsx/bds/implements.ts
bdsx/bds/pdb.ini
bdsx/bds/symbols.ts

I added `Actor::isSneaking` to class `Actor`.
It's also possible with ActorFlags, but I think that this would be simpler.

add 'Actor::isSneaking'

---

bdsx/bds/implements.ts
bdsx/bds/level.ts
bdsx/bds/packets.ts
bdsx/bds/pdb.ini
bdsx/bds/symbols.ts
bdsx/event.ts
bdsx/event_impl/blockevent.ts

idk if the name of BlockDestructionStartEvent is ok

Implement BlockDestructionStartEvent and Level.prototype.getCurrentTick

---

bdsx/bds/actor.ts
bdsx/bds/implements.ts
bdsx/bds/pdb.ini
bdsx/bds/symbols.ts

Add: ActorDamageCause::setCause

add ActorDamageCause::setCause

---

bdsx/bds/implements.ts
bdsx/bds/level.ts
bdsx/bds/pdb.ini
bdsx/bds/symbols.ts

Added :
`getRuntimeEntity` and `getRuntimePlayer`.
Changed :
parameters' name in `fetchEntity`. because to follow BDS official name(`fetchRemovedActor`->`getRemoved`), and to keep consistency(`id` -> `runtimeId`)
I welcome some advice, always

Add: getRuntimeEntity & getRuntimePlayer

---

bdsx/bds/command.ts
bdsx/bds/pdb.ini
bdsx/bds/symbols.ts
example_and_test/customcommand.ts

Add: Methods for `CommandPosition`, and an example

Add: Methods for `CommandPosition`

---

bdsx/bds/actor.ts
bdsx/bds/implements.ts

Fix typo: `isVaild` -> `isValid`

Fix typo: `isVaild` -> `isValid`

---

bdsx/bds/gamerules.ts

Add: mores value in `GameRuleId`.

Add: more values in `GameRuleId`.

---

bdsx/bds/actor.ts
bdsx/bds/implements.ts

Add `Actor.getTags`.
it returns tags from the entity's NBT.
because original `Actor.getTags` from BDS uses `gsl::span<std::string>` type, not implmeneted in bdsx yet.

add `Actor.getTags`

---

bdsx/bds/implements.ts
bdsx/bds/server.ts

Fixed typo.
`VanilaServerGameplayEventListener` -> `VanillaServerGameplayEventListener`
I fixed a typo.
I made old one extends from new one.
but I'm not sure it's correct way.

fix `VanillaServerGameplayEventListener` typo

---

bdsx/event_impl/entityevent.ts

fix the PlayerJoinEvent gives a ServerPlayer but on the class its variable is defined on the Player class

fix variable type

---

example_and_test/customcommand.ts

`example_and_test/customcommand.ts` : Added multiple overloads example

Multiple command overloads example

---

bdsx/bds/command.ts
bdsx/bds/implements.ts
bdsx/bds/inventory.ts
bdsx/bds/packetids.ts
bdsx/bds/packets.ts
bdsx/bds/pdb.ini
bdsx/bds/symbollist.ts
example_and_test/test.ts

Various changes. but the main one is for packets. 
1. Fix some components in`MinecraftPacketIds`. To follow the official name. - I'm not sure whether there is something I missed.
2. Implement **parts of** `UpdateTradePacket`. I believe it's not everything, but still, there are necessary things.
3. Use `Actor::startRiding` for `Actor.prototype.startRiding` instead of vftable offset. it seems it still works with Actor::startRiding even is a Mob.

Update some packets

---

bdsx/bds/command.ts
bdsx/bds/pdb.ini
bdsx/bds/symbollist.ts

Implement `CommandSelectorBase::getName` for `ActorCommandSelector`, `PlayerCommandSelector`, `ActorWildcardCommandSelector`, `PlayerWildcardCommandSelector`
Sometimes when you want to input a player name but the player is offline, this helps to get the input text

Implement `CommandSelectorBase::getName`

---

bdsx/bds/actor.ts
bdsx/bds/attribute.ts
bdsx/bds/packets.ts

Implement `SetActorLinkPacket` and a bit of `AddActorPacket`
It allows to ride any entity

Implement `SetActorLinkPacket`

---

example_and_test/customcommand.ts

Added an example command for soft enums.
The command allows you to add/remove soft enum values, and to list them.

Soft enum example

---

bdsx/bds/packets.ts

Add packet fields
Add `RespawnPacket` and `SetSpawnPositionPacket` fields so scripts can read and manipulate them

Add `RespawnPacket` and `SetSpawnPositionPacket`

---

bdsx/bds/actor.ts
bdsx/bds/implements.ts

Added `Actor.prototype.getSpeedInMeterPerSecond`

add Actor.prototype.getSpeedInMeterPerSecond

---

bdsx/bds/block.ts
bdsx/bds/implements.ts

Implement Block.getDestroySpeed and BlockLegacy.getDestroySpeed.

Implement Block.getDestroySpeed and BlockLegacy.getDestroySpeed.

---

.eslintrc.json

A very little changed.
When filter importing by relative path, simplified pattern condition in `no-restricted-patterns`, to `**/*/bdsx`.
Actually nothing special..
but it has shortened.

Simplify pattern condition in `no-restricted-patterns`

---

bdsx/bds/implements.ts
bdsx/bds/structure.ts

Implemented StructureTemplate.save() and StructureTemplate.load()
Following how they are implemented for ItemStackBase, I added them for StructureTemplate. Makes it easier to modify structures
They are both methods I need to use and implementing them here is cleaner than doing it in my own code

Implement StructureTemplate save and load

---

bdsx/bds/blockpos.ts

directionFromRotation is useful for sending rays from a given position based on rotation, in my usecase for sending a ray from the player to see what block they are looking at.
Its something I use for a few plugins I'm working on

Implemented directionFromRotation and rotationFromDirection on Vec3

---

bdsx/bds/blockpos.ts

Improves consistency between Vec2 and the other Vector types
I have my own form of Vectors for writing to file, and being able to just pass it through the create method on Vec2 would be helpful in keeping things consistent

Added create(VectorXY) for Vec2

---

bdsx/commandenum.ts

Fixed a bug where the method called setValues ​​in "SoftEnum" did not work properly.
It has been corrected due to an error in which the user list does not appear correctly while creating the ban command.

softenum bugfix

---

bdsx/event.ts
bdsx/event_impl/blockevent.ts

Add `PistonCheckEvent`
This event can be used to prevent blocks being moved by the piston. Special thanks to SacriPudding.

Add PistonCheckEvent

---

.prettierignore
bdsx/bds/actor.ts
bdsx/bds/implements.ts
example_and_test/customcommand.ts
example_and_test/event-jump.ts
example_and_test/test.ts

Add Actor.getVariant and Actor.setVariant.

Add Actor.getVariant and Actor.setVariant

---

bdsx/bds/packets.ts

Implement MoveActorAbsolute Packet
I was need it to fix Entity Fly/Speed etc.

Add MoveActorAbsolute Packet

---

bdsx/event.ts
bdsx/event_impl/entityevent.ts

Typo Fix, removed invalid 'readonly'
We can change the new health!
I hate that the red line appears even though it's not causing a runtime error.
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)

Typo Fix, Invalid readonly fix

---

bdsx/bds/form.ts
bdsx/storage/index.ts
example_and_test/ipban.ts
example_and_test/storage.ts

Adds:
- Generics to storage for those who want type safety in storage
- Form set/add functions now return this
- This is useful for situations like this:
```ts
const form = new CustomForm()
.addComponent(new FormDropdown("Dropdown 1", ["a", "b", "c"]))
.addComponent(new FormDropdown("Dropdown 2", ["x", "y", "z"]))
.addComponent(new FormDropdown("Dropdown 2", ["1", "2", "3"]));
```
To add safe typing to BDSX's storage and make forms more convenient to use.
-   [X] New feature (non-breaking change which adds functionality)
-   [X] My code follows the code style of this project.
-   [X] I have tested my changes and confirmed that they are working

Optional type safety for BDSX storage and stacking form components

---

bdsx/bds/actor.ts
bdsx/bds/packets.ts

Updated ActorDamageCause based on Official Protocol Docs
ref:
https://mojang.github.io/bedrock-protocol-docs/html/enums.html  
https://github.com/Mojang/bedrock-protocol-docs

Update ActorDamageCause enum

---

bdsx/bds/actor.ts
bdsx/bds/implements.ts
bdsx/bds/packets.ts

Added a method `Actor.playAnimation()` which broadcasts an animation of actor and implemented `AnimateEntityPacket` structure to send it.

Implemented `Actor.playAnimation()` and `AnimateEntityPacket`
