- bdsx/installer/installer.ts
- update.sh
NPM refuses to run the postinstall script if ran as root (which is the case with the official Dockerfile, which is broken for this reason), unless `--unsafe-perm` is provided.
Additionally, the server download script (`install.ts`) hangs waiting for user input when ran from a non-interactive shell (like `docker-compose`). This PR also fixes that.
> Make it run under Docker

- bdsx/installer/installer.ts
This is the second part of #39, which is still needed, otherwise the installer will hang. (I moved the `readline.createInterface` call)
> Fix installer hanging with BDS_YES=true

- bdsx/pdbparser/parse.ts
Fixed an error that aborted the process if the globals folder didnt exist when running the pdb parser.
> Fixed error if "globals" folder didnt exists

- package-lock.json
- package.json
The library node-html-parser relies through another library on an old version of "css-what". css-what has a recently released vulnerability with a High severity rank due to it's ability to be used for a DoS attack.
Info on the vulnerability can be found on the npm site at https://www.npmjs.com/advisories/1754 or by running npm audit.
Version 3.3.5 of node-html-parser is automatically chosen by npm as the earliest version with the fixed version of css-what (being version 5.0.1).
> Update node-html-parser to v3.3.5

- bdsx/event_impl/entityevent.ts
Since this event does not need to be cancelable, I think it should fire afterwards. This led to several hard to trace bugs in my code relating to executing commands selecting the player in this event. 
I think the event should represent after the player is joined and ready to be used. However, this is more of a design desision, so since @Rjlintkh wrote it it's up to them to choose whether to do it.
> PlayerJoinEvent fire after packet instead of before

- bdsx/nativeclass.ts
Every time I want to log a packet I need to log the fields and values one by one which is annoying, this adds a method for all NativeClass to convert the fields into JSON record. Do run it with allocated NativeClass only, otherwise Access Violation.
Is there anything I can improve on this?
> Add a toJSON for NativeClass for easier logging

- example_and_test/net-ping.ts
For this commit, it uses `serverInstance.networkHandler` instead of `serverInstance.minecraft.getNetworkHandler()` (net-ping.ts)
I didn't know that there is `serverInstance.networkHandler`
so simple changes, but can you accept this request please?
> use networkHandler shorter

- bdsx/bds/actor.ts
- bdsx/bds/implements.ts
- bdsx/bds/level.ts
- bdsx/bds/pdb.ini
- bdsx/bds/symbols.ts
Implemented `Level.getTime()`, `Level.setTime()` + `Actor.getLevel()` functions.
- Hooks `Level::getTime`
- Returns the current level time (in ticks)
- Hooks `Level::setTime`
- Sets the level time
- Syncs the level time with clients (by sending a `SetTimePacket`)
- Hooks `Actor::getLevel`
- Returns a `Level` instance
- Allows to get the level instance in a simpler way
*nb: `Level::getTime` & `Level::setTime` call `LevelData::getTime` & `LevelData::setTime` in the BDS source code, but i felt it was more appropriate to implement them in the `Level` class (it also does not make any difference)*
> Level time functions implementation

- bdsx/bds/actor.ts
- bdsx/bds/command.ts
- bdsx/bds/implements.ts
- bdsx/bds/typeid.ts
- example_and_test/customcommand.ts
I added `PlayerWildcardCommandSelector`
Now, we don't need to check with `Actor.isPlayer` for the return value of `newResults(origin)` individually when only players are required.
> PlayerWildcardCommandSelector

- bdsx/bds/pdb.ini
- bdsx/bds/player.ts
- bdsx/bds/symbols.ts
- bdsx/event.ts
- bdsx/event_impl/entityevent.ts
Implemented `PlayerLeftEvent`, using `ServerNetworkHandler::_onPlayerLeft`, as suggested on the discord server
Added missing `color` parameter in the `ServerPlayer.setBossBar()` docstring
<details>
<summary>Credits</summary>
Credits to @ambiennt for the `skipMessage` parameter name xd (https://media.discordapp.net/attachments/819817286264684564/920444941086388234/unknown.png)
</details>
> PlayerLeftEvent implementation

- bdsx/bds/actor.ts
- bdsx/bds/implements.ts
- bdsx/bds/pdb.ini
- bdsx/bds/symbols.ts
- bdsx/event_impl/entityevent.ts
There is no `Actor::setName`, but there are `Actor::setNameTag`, and `Player::setName`.
They are not overridden.
`Actor::setNameTag` doesn't affect for player name in chat.
Added some comments for the methods
> following BDS official name

- bdsx/bds/actor.ts
- bdsx/bds/implements.ts
- bdsx/bds/pdb.ini
- bdsx/bds/symbols.ts
I added a method to damage the entity.
Actually, I wanted to use `_` as a **prefix** for `Actor.hurt_` like `Actor._hasEffect`, `Actor._getArmorValue`, `Player._setName` ..., but I couldn't because `Player::_hurt` existed in BDS already.
> add Actor.hurt

- bdsx/bds/implements.ts
- bdsx/bds/pdb.ini
- bdsx/bds/player.ts
- bdsx/bds/symbols.ts
Added XP related functions in the `Player` class.
---
`Player.addXp` hooks `Player::addExperience` (name changed for consistency with the other functions)
`Player.addXpLevels` hooks `Player::addLevels` (name changed for consistency with the other functions, also `getLevel` would have been confusing) 
`Player.getXpNeededForNextLevel` hooks `Player::getXpNeededForNextLevel`
I did not find any other player XP related native function.
The other functions use :
- the functions above
- the actor attributes, with `Actor.setAttribute` & `Actor.getAttribute`
These functions allow easy XP management for developers
See docstrings for usage
<details>
<summary>Credits</summary>
<br>
🐢
</details>
> XP Functions implementation

- bdsx/bds/implements.ts
- bdsx/bds/player.ts
- bdsx/bds/server.ts
Add :
`sendTextObject` - its type, `TextPacket.Types.TextObject` is used on `tellraw` also.
some interfaces and type for `sendTextObject`.
Fix :
text packet type for `sendWhisper`.
some missing `.dispose()` for the packets.
> Changes at using `Packet`

- bdsx/bds/nbt.ts
Before:
it was accessed to setter, so output of
```js
console.log(NBT.int(10).value)
```
was `undefined`
Now:
it accesses to getter, so its output is normal.
> Fix: getters for NBT Numeric classes

- bdsx/bds/block.ts
- bdsx/bds/pdb.ini
- bdsx/bds/symbols.ts
- bdsx/event.ts
- bdsx/event_impl/blockevent.ts
I added `events.buttonPress`, but there are two things to discuss.
1. the event is cancellable with considering two facts:
- the client can see motion and sound
- but in server-side, the event will be canceled, it doesn't turn redstone signal on.
is it correct that `cancellable`?
2. I think a property name `pressingDirection` is a bit long. but I'm worried about changing to just `direction` makes people misunderstanding that is for direction of button placed.
> add `events.buttonPress`

- bdsx/bds/command.ts
Fix `constructSharedPtr` for `executeCommand`.
makes the `constructSharedPtr` returns a valid pointer.
Fix `constructSharedPtr` for `executeCommand`.
but I'm not sure that
***ctx, origin: no need to destruct, it's destructed by internal functions.***
means they will be destructed by BDS. if false, they must be destructed in each `runCommand` or `executeCommand`
> fix `constructSharedPtr` - now returns valid a shared pointer

- bdsx/bds/actor.ts
- bdsx/bds/implements.ts
I added `Actor.getFeetPos`.
existing `Actor.getPosition` returns with Y of entity's head position.
In fact, `Actor.getFeetPos` is not from BDS. but I think it is more useful than `Actor.getPosition` in a lot cases because it returns a position same with the coordinates shown to the client .
> add `Actor.getFeetPos`

- bdsx/bds/actor.ts
- bdsx/bds/implements.ts
- bdsx/bds/pdb.ini
- bdsx/bds/player.ts
- bdsx/bds/symbols.ts
I added `Mob.knockback`, and other things to achieve it.
Now, we can make knockback to other mobs like pigs, cows, creepers ... etc.
Changed:
- new class `Mob` is added. I'm confused about it would be better with being in `mob.ts`
- `Player` inherits from `Mob`, not `Actor`.
- `ServerPlayer.knockback` is removed. it uses one inherited from `Mob`.
I've tested they are working with below code:
```js
import { ActorType } from "bdsx/bds/actor";
import { ActorCommandSelector, CommandPermissionLevel } from "bdsx/bds/command";
import { command } from "bdsx/command";
command.register("knockback", "knockback", CommandPermissionLevel.Operator).overload(
(p, o, op) => {
for (const entity of p.entities.newResults(o)) {
if (entity.isMob()) {
entity.knockback(null, 0, 0, 0, 1, 2, 2);
}
}
},
{ entities: …
```
> Add `Mob.knockback`

- bdsx/bds/implements.ts
- bdsx/bds/inventory.ts
- bdsx/bds/pdb.ini
- bdsx/bds/symbols.ts
Separating `ItemStack` and `ItemStackBase`
`ItemStack` is different from `ItemStackBase` even `ItemStack` inherits from `ItemStackBase`.
so I separated them.
Changes to look out for:
* Before:
- `ItemStack.prototype.load` used `static ItemStack::fromTag`.
- `ItemStack.prototype.toString` and `ItemStack.prototype.toDebugString` used `ItemStackBase.prototype.*` ones. (not overridden).
* After:
- `ItemStack.prototype.load` is inherited from `ItemStackBase.prototype.load`.
- `ItemStackBase.prototype.toString` and `ItemStackBase.prototype.toDebugString` are called with overridden functions.
- `ItemStack.fromTag` is added.
> Separating `ItemStack` and `ItemStackBase`

- bdsx/bds/blockpos.ts
- bdsx/bds/implements.ts
- bdsx/bds/pdb.ini
- bdsx/bds/player.ts
- bdsx/bds/symbollist.ts
- Added `Actor.playSound()` (using `PlaySoundPacket`), allowing developers to easily play sounds client-side
- Implemented `Player.getXuid()`, (`Player::getXuid` internally), allowing you to get players' xuids without needing to get their certificate
- Added an overload to `BlockPos.create()`, which now allows `Vec3` or `x y z` coordinates to be used
> Actor.playSound(), Player.getXuid(), BlockPos overload

- bdsx/bds/implements.ts
- bdsx/bds/inventory.ts
- bdsx/bds/pdb.ini
- bdsx/bds/symbollist.ts
add `NetworkItemStackDescriptor.prototype.moveFrom`
Now we can set the value of `NetworkItemStackDescriptor` for fields in some packets.
I named the function as `moveFrom`, but I wonder if it would be better to name as `set` like `BlockPos` or `Vec3`.
> add `NetworkItemStackDescriptor.prototype.moveFrom`

- bdsx/pdbcache.ts
add pdbcache EOF detection
The iterator returned by pdbcache.readKeys() will continue reading cache when reaching EOF, causing loadAllSymbols throwing error "Attempt to allocate 2GB Buffer"
> Fix pdbcache.readKeys() never done

- bdsx/bds/actor.ts
- bdsx/bds/implements.ts
- bdsx/util.ts
implemented `ActorDamageByActorSource`.
we can set damaging entity (attacker) for `hurt` or `die` ..
but its constructor requires an `Actor`. and it conflicts with `ActorDamageSource` one.
I wanted to keep its name as `constructWith`.
so I wrote multiple overloads first, then made to throw an error in invalid overload.
I wonder if there is any alternative way.
> Implement 'ActorDamageByActorSource`.

- bdsx/addoninstaller.ts
By changing the module type javascript to script, the issue that some add-ons cannot be loaded.
Starting with 1.19, the module type javascript was removed and script was added instead.
[1.19 ChangeLog](https://feedback.minecraft.net/hc/en-us/articles/6613754674829)
As a result, behavior packs containing GameTest created for 1.19 and later can no longer be loaded.
This pull request fixes this issue.
> Fixed an issue where some behavior packs could not be loaded.

- bdsx/installer/installerapi.ts
User can specify following environment variables to change the behavior of installer.
- `BDSX_BDS_VERSION` - BDS version
- `BDSX_CORE_VERSION` - BDSX Core version
- `BDSX_BDS_LINK` - BDS download URL
- `BDSX_CORE_LINK` - BDSX Core download URL
- `BDSX_PDBCACHE_LINK` - PDBCache download URL
GitHub is sometimes slow or unaccessible in China mainland, so I build a mirror for BDSX Core and PDBCache.
So I can just execute the following batch script `updateCN.bat` to update:
```batch
@echo off
set BDSX_CORE_LINK=https://bdsx.projectxero.top/bdsx-core-package/bdsx-core-%%BDSX_CORE_VERSION%%.zip
set BDSX_PDBCACHE_LINK=https://bdsx.projectxero.top/pdbcache/pdbcache-%%BDS_VERSION%%.zip
call ./update.bat
```
> Installer can read url from environment variables

- bdsx/command.ts
Fix the Type error.
In 018d36507b4574233554e17140eff3e1693a1a9f, a test was failed because of a type error in generic (`command.overload`).
it seems it cannot recognize the `OPTS` is based on `CommandFieldOptions | boolean`.
so I changed it to check `OPTS` but I'm not sure whether it makes sense.
> Try to fix type error.

- bdsx/bds/nbt.ts
NBT.parse was unable to parse snbt if it contained a key with a leading "z". 
This pull request fixes this bug.
```
{Findable:0b,Items:[{Count:3b,Damage:0s,Name:"minecraft:written_book",Slot:0b,WasPickedUp:0b,tag:{author:"Author Unknown",generation:0,title:"test",xuid:"2535430734530126"}},{Block:{name:"minecraft:lectern",states:{direction:0,powered_bit:0b},version:17959425},Count:64b,Damage:0s,Name:"minecraft:lectern",Slot:1b,WasPickedUp:0b},{Block:{name:"minecraft:enchanting_table",states:{},version:17959425},Count:64b,Damage:0s,Name:"minecraft:enchanting_table",Slot:2b,WasPickedUp:0b},{Block:{name:"minecraft:chest",states:{facing_direction:0},version:17959425},Count:1b,Damage:0s,Name:"minecraft:chest",Slot:3b,WasPickedUp:0b},{Block:{name:"minecraft:chest",states:{facing_direction:2},vers …
```
> Fix bug when parse some snbt.

- bdsx/bds/packets.ts
Added customSkinDisabled field to LevelSettings, allows for custom skins to easily be disabled when hooking the StartGame packet
Someone asked me how to disable custom skins and this field is what allows you to do that
> Added customSkinDisabled field to LevelSettings

- bdsx/bds/form.ts
- bdsx/bds/packets.ts
- example_and_test/form.ts
Implemented `cancelationReason` in `ModalFormResponsePacket`.
I implemented `cancelationReason` for `Form`.
now we can check the reason why the form was canceled. (when the response is `null`)
but I couldn't set a property for `cancelationReason` because the existing system has a structure that returns just `null`.
so I made a method that is called `getLastCancelationReason` in `Form`.
I'm not sure if this is fit for bdsx.
> impl: Form.CancelationReason

- bdsx/bds/command.ts
- example_and_test/customcommand.ts
- example_and_test/net-disconnect.ts
`PlayerCommandSelector.newResults` returns only an array of `ServerPlayer`
`PlayerCommandSelector.newResults` returns only an array of `ServerPlayer`.
Now it is unnecessary to use `.newResults(origin, ServerPlayer` to filter `ServerPlayer`.
> override type of returns of newResults - CommandSelector

- bdsx/bds/actor.ts
- bdsx/bds/implements.ts
- bdsx/bds/player.ts
removed deprecated function `Actor.prototype.getName()`
add new function `Player.getName()`
change deprecated function
need to add a function to get real name of a player.
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] My code follows the code style of this project.
> Add `Player.getName()`

- bdsx/event.ts
- bdsx/event_impl/entityevent.ts
Implements event.playerInteract
Implements PlayerInteractEvent, which triggers on player interaction with entity using RMB, or holding on a touchscreen
Pretty useful event, I needed it multiple times, and I think other's too
> BDSX: Implement PlayerInteractEvent

- bdsx/bds/packets.ts
This PR adds support for `ShowCreditsPacket`, `NpcRequestPacket`, `ShowProfilePacket`, `NetworkChunkPublisherUpdatePacket`, `BiomeDefinitionList`, `LecternUpdatePacket`, `ClientCacheStatusPacket`, `MapCreateLockedCopy`, and `EmotePacket`.
This will allow developers to use more packets, for example this could be used to show end credits to someone, make some do an emote or display a profile.
-   [X] New feature (non-breaking change which adds functionality)
-   [X] My code follows the code style of this project. (Yes it was very painful undoing all of the autoformatting that is enabled in this project that for some reason doesn't follow this project's style)
-   [X] I have tested my changes and confirmed that they are working
> Support for more packets

- bdsx/externs/generated.addons.d.ts
Wool is now free of data values
Mojang changed wool from using data values, to unique id for every wool. Like: orange_wool, etc.
Even though wool with data values can still be used in some places, you cannot use it in ItemStack, or Block, and I`m not sure if there's any place in bdsx where it can be used
-   [x] Bug fix (non-breaking change which fixes an issue)
> BDSX: Fix wool ids in BlockIdMap and ItemIdMap interfaces

- bdsx/bds/actor.ts
- bdsx/bds/inventory.ts
- bdsx/bds/player.ts
The Minecraft Wiki maintainers have decided to move away from Fandom. More information can be found here: https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom. This PR updates all the URLs to the new domain: minecraft.wiki
> Update Minecraft Wiki links to new domain after fork

- bdsx/bds/skin.ts
- bdsx/mce.ts
Fixed offset of blob in mce.Image needed to get skin image
After updating to 1.20.50, I couldn't get the correct skin image, so I was looking for memory around the Image.blob and found the offset was off.
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
> fix mce.Image blob offset

- bdsx/common.ts
- bdsx/cxxvector.ts
- bdsx/nativeclass.ts
- example_and_test/test.ts
- Added `toTypeArray` and `setFromTypedArray` methods to `CxxVector` for more efficient operations with vectors containing primitive values.
- These new methods, `toTypedArray` and `setFromTypedArray`, are faster than the existing `toArray` and `setFromArray` methods, especially when dealing with large arrays.
- This is a part of the migration from `TagMemoryChunk` to `CxxVector` for `ByteArrayTag` and `IntArrayTag`.
- Starting from BDS 1.20.60 (which will be released soon), `ByteArrayTag` and `IntArrayTag` have migrated its underlying data structure from `TagMemoryChunk` to `std::vector`.
- For more details about this migration, please refer to [this commit](https://github.com/XeroAlpha/bdsx/commit/56a2f0923b9e1ebcd38f768ca8c360159604e4ed#diff-b6f2817a27f351eff45b8b26aedc59af016aa256ea544 …
> add CxxVector.toTypedArray and setFromTypedArray

- bdsx/bds/block.ts
- bdsx/bds/implements.ts
The BDS now defaults to hashing the runtime ID rather than it being incremental. This means that it is far more common an ID is going to go over the int32 limit.
When it does go over a limit it prevents the value from being comparable between the value you get from the method and the value used in packet fields. Discovered this when attempting to read the UpdateBlock packet for a specific block.
-   [X] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [X] My code follows the code style of this project.
-   [X] I have tested my changes and confirmed that they are working
> Updated Block::getRuntimeId to return UInt32 rather than Int32

- bdsx/bds/implements.ts
- bdsx/bds/level.ts
Implemented setters/getters for RainLevel, RainTime, LightningLevel, and LightningTime
Working on a plugin that interacts with these and wanted to create an easy way to query the info. I didn't need the setters but thought I should add them since they exist
-   [X] New feature (non-breaking change which adds functionality)
-   [X] My code follows the code style of this project.
-   [X] I have tested my changes and confirmed that they are working
> Added weather related functions to LevelData

- bdsx.sh
Fixes an error message.
This pull requests resolves the following error message appearing in Linux platforms:
```./bdsx.sh: 37: [: 1: unexpected operator```
By using the correct operator for comparing integers in [man test](https://linux.die.net/man/1/test).
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
> use eq and ne operators for integer comparison

- bdsx/bds/actor.ts
- bdsx/event_impl/entityevent.ts
Filled `ActorInitializationMethod` enum which was empty, and add `EntityCreatedEvent#method` property to retrieve its cause of creation.
I used [EntityInitializationCause](https://learn.microsoft.com/en-us/minecraft/creator/scriptapi/minecraft/server/entityinitializationcause?view=minecraft-bedrock-stable) in ScriptAPI as a reference.  
Also, I suggest renaming the event from `EntityCreatedEvent` to `ActorCreatedEvent` for consistent naming
> Fill `ActorInitializationMethod` and add `method` property to EntityCreatedEvent
